title: 北京振华学校
default_lang: zh
author:
  name: 'Fang Yun'
  email: fangyuncn@163.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
